title: distrainer
description: block-native distributed training on Ray Train
markdown: kramdown
kramdown:
  input: GFM
plugins:
  - jekyll-relative-links
  - jekyll-optional-front-matter
relative_links:
  enabled: true
  collections: true
defaults:
  - scope:
      path: ""
    values:
      layout: default
exclude:
  - README.md
